### ISSUE TITLE
Unable to access video when deployed in heroku.

### ISSUE THREAD

**Issue by Pitzcarraldo** [jaimeMF/youtube-dl-api-server#33]
First, thank you for made useful app like this.

I deployed this repository in my heroku server with no change.
And I request to url like below, but video urls in response is return 403 forbidon. 

http://traktrax-video-api.herokuapp.com/api/info?url=https://www.youtube.com/watch?v=OPf0YbXqDm0

However, response of same request to your example server is return right video.

http://youtube-dl.appspot.com/api/info?url=https://www.youtube.com/watch?v=OPf0YbXqDm0

What is difference of between servers?

I check issue for similar status, but I couldn't find solution. 
https://github.com/jaimeMF/youtube-dl-api-server/issues/3

Is master branch deployed on the youtube-dl.appspot.com?

Thank you :)

**Comment by jaimeMF** [comment]
> Is master branch deployed on the youtube-dl.appspot.com?

Yes, and it shouldn't matter too much since I don't do anything really special, essentially it just runs youtube-dl.

I can't do anything, I guess it depends on the location of the server and some other factor I can't control. And actually youtube-dl only guarantes that the url can be used from the same computer and with the same cookies.
