### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by java4fun** [jaimeMF/youtube-dl-api-server#38]
Hi, 
I downloaded the project to my Windows 7 PC (python 3.3).  I tried to run the server on my PC. Got the following error:

// 20151206212422
// http://localhost:9191/api/info?url=http://www.ted.com/talks/dan_dennett_on_our_consciousness.html&flatten=False

{
  "error": "ERROR: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547)'),))"
}

Is there a workaround for testing purpose?

**Comment by jaimeMF** [comment]
Add `'nocheckcertificate': True,`after [this line](https://github.com/jaimeMF/youtube-dl-api-server/blob/4ecd9cf7dd3c6fc9827afe2b655ca09084fc7eff/youtube_dl_server/app.py#L29). Unfortunately on Windows some people have the same problem when directly using youtube-dl (https://github.com/rg3/youtube-dl/issues/7309).

**Comment by zaasmi** [comment]
same issue still after adding 
youtube-dl.exe http://www.youtube.com/watch?v=qn6CMz18lkQ 'nocheckcertificate': True,
[youtube] qn6CMz18lkQ: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

**Comment by jaimeMF** [comment]
@zaasmi This is not the bug tracker for youtube-dl, see https://github.com/rg3/youtube-dl/issues/7309 for more info.
